/**
 * StarRating — PCF (Power Apps Component Framework)
 *
 * This component replaces numeric and text fields in Dynamics 365 /
 * Power Apps with a visual star rating interface, a comment field,
 * and dynamic record cards loaded from a JSON field.
 *
 * Properties mapped in the form:
 *  - value       → numeric field (Whole Number) — rating from 1 to 5
 *  - comment     → text field (Single Line)     — user comment
 *  - recordsJson → long text field (Multiple)   — JSON with cards
 */

// IInputs and IOutputs are interfaces automatically generated by the build
// from ControlManifest.Input.xml — they define the types of each property
import { IInputs, IOutputs } from "./generated/ManifestTypes";

// The class implements the standard PCF interface
// ComponentFramework.StandardControl<IInputs, IOutputs> enforces the class
// to have the 4 lifecycle methods: init, updateView, getOutputs, destroy
export class StarRating implements ComponentFramework.StandardControl<IInputs, IOutputs> {

  // Reference to the root HTML element where the component is rendered
  // Dynamics injects this container into the form
  private _container: HTMLDivElement;

  // Stores the current rating (1 to 5) in memory
  // Updated when the user clicks a star
  private _currentValue: number;

  // Stores the comment text in memory
  // Updated while the user is typing (via debounce)
  private _currentComment: string;

  // Stores the raw JSON string from the form field
  // Example: [{ "id":"1", "text":"...", "color":"#fff", "copyEnabled":true }]
  private _recordsJson: string;

  // Function provided by Dynamics to signal that a value has changed
  // When called, Dynamics executes getOutputs() to retrieve the new value
  private _notifyOutputChanged: () => void;

  /**
   * init — Lifecycle #1
   *
   * Called ONCE when the component is loaded into the form.
   * Responsible for: setting up variables, registering callbacks,
   * and performing the first render.
   *
   * @param context             — object with all form data and PCF utilities
   * @param notifyOutputChanged — callback to signal Dynamics that a value changed
   * @param state               — state persisted between sessions (not used here)
   * @param container           — HTML element where the component will be rendered
   */
  public init(
    context: ComponentFramework.Context<IInputs>,
    notifyOutputChanged: () => void,
    state: ComponentFramework.Dictionary,
    container: HTMLDivElement
  ): void {
    // Saves the container for use in rendering methods
    this._container = container;

    // Applies the root CSS class for Fluent UI native styling
    this._container.classList.add("star-rating-container");

    // Saves the callback — will be called whenever the user interacts
    this._notifyOutputChanged = notifyOutputChanged;

    // Reads the initial values from the mapped form fields
    // The ?? operator ensures a default value if the field is empty
    this._currentValue   = context.parameters.value.raw       ?? 0;
    this._currentComment = context.parameters.comment.raw     ?? "";
    this._recordsJson    = context.parameters.recordsJson.raw ?? "[]";

    // First render of the component
    this.renderStars();
  }

  /**
   * updateView — Lifecycle #2
   *
   * Called by Dynamics every time any form value changes
   * (any field, not just the ones mapped to this component).
   * Must sync internal state with the new values and re-render.
   *
   * @param context — updated object with the latest form values
   */
  public updateView(context: ComponentFramework.Context<IInputs>): void {
    // Updates all internal variables with the latest values
    this._currentValue   = context.parameters.value.raw       ?? 0;
    this._currentComment = context.parameters.comment.raw     ?? "";
    this._recordsJson    = context.parameters.recordsJson.raw ?? "[]";

    // Re-renders the component with the new values
    this.renderStars();
  }

  /**
   * getOutputs — Lifecycle #3
   *
   * Called by Dynamics right after notifyOutputChanged() is executed.
   * Must return the current values to be saved to the form fields.
   * The return must match the "bound" properties defined in the manifest.
   */
  public getOutputs(): IOutputs {
    return {
      value:   this._currentValue,   // → saved to the rating_value field
      comment: this._currentComment  // → saved to the rating_comment field
    };
  }

  /**
   * destroy — Lifecycle #4
   *
   * Called when the component is removed from the form.
   * Use to clean up event listeners, timers, or open connections.
   * No external resources to release in this component.
   */
  public destroy(): void {
    // No external resources to release in this component
  }

  /**
   * renderStars — private main rendering method
   *
   * Rebuilds the entire component DOM from scratch.
   * Called in init (first time) and in updateView (on updates).
   *
   * Generated structure:
   *  container
   *  ├── span.star (x5)     — clickable stars
   *  ├── textarea           — comment field
   *  ├── hr.divider         — visual separator
   *  └── renderRecords()    — record cards
   */
  private renderStars(): void {
    // Clears the previous DOM before re-rendering
    // Ensures no duplicate elements will exist
    this._container.innerHTML = "";

    // ── Stars ─────────────────────────────────────────────────
    // Creates 5 stars numbered from 1 to 5
    for (let i = 1; i <= 5; i++) {
      const star = document.createElement("span");

      // ★ = filled star (active), ☆ = empty star (inactive)
      star.innerText = i <= this._currentValue ? "★" : "☆";

      // Base class + state class (active/inactive)
      // CSS uses these classes to apply the correct colors
      star.classList.add("star-rating-star");
      star.classList.add(i <= this._currentValue ? "active" : "inactive");

      // On click: updates the value, notifies Dynamics, and re-renders
      star.onclick = () => {
        this._currentValue = i;
        this._notifyOutputChanged(); // signals Dynamics → it calls getOutputs()
        this.renderStars();          // re-renders to reflect the new rating
      };

      this._container.appendChild(star);
    }

    // ── Comment textarea ──────────────────────────────────────
    const textarea = document.createElement("textarea");
    textarea.value       = this._currentComment;
    textarea.placeholder = "Leave a comment...";
    textarea.classList.add("star-rating-textarea");

    // Debounce timer — prevents calling notifyOutputChanged on every keystroke
    // The variable is declared outside the event to persist between calls
    let debounceTimer: ReturnType<typeof setTimeout>;

    textarea.oninput = () => {
      // Updates the internal variable immediately on each keystroke
      this._currentComment = textarea.value;

      // Cancels the previous timer (if the user is still typing)
      clearTimeout(debounceTimer);

      // Only notifies Dynamics 800ms after the last keystroke
      // Prevents re-renders while the user is typing
      debounceTimer = setTimeout(() => {
        this._notifyOutputChanged();
      }, 800);
    };

    this._container.appendChild(textarea);

    // ── Visual divider ────────────────────────────────────────
    // Horizontal line separating the comment from the record cards
    const divider = document.createElement("hr");
    divider.classList.add("star-rating-divider");
    this._container.appendChild(divider);

    // ── Record cards ──────────────────────────────────────────
    // Delegates card rendering to the dedicated method
    this.renderRecords();
  }

  /**
   * renderRecords — private method to render JSON record cards
   *
   * Reads the JSON from the recordsJson field, parses it, and creates
   * a card for each record. Each card can have its own color and copy
   * button configured individually via the JSON.
   *
   * Expected JSON structure:
   * [
   *   {
   *     "id": "1",               — unique identifier for the record
   *     "text": "...",           — text displayed on the card
   *     "color": "#0078d4",      — background color in hex
   *     "copyEnabled": true      — shows or hides the copy button
   *   }
   * ]
   */
  private renderRecords(): void {
    // Defines the type of each JSON item for TypeScript to validate
    let records: { id: string; text: string; color: string; copyEnabled: boolean }[] = [];

    try {
      // Converts the JSON string into an array of objects
      records = JSON.parse(this._recordsJson);
    } catch {
      // If the JSON is invalid, exits without rendering anything
      // Prevents the component from breaking due to malformed data
      return;
    }

    // If the array is empty, does not render the container
    if (records.length === 0) return;

    // Container that groups all cards
    const recordsContainer = document.createElement("div");
    recordsContainer.classList.add("star-rating-records");

    // Iterates over each JSON record and creates its card
    records.forEach(record => {

      // ── Card ────────────────────────────────────────────────
      const card = document.createElement("div");
      card.classList.add("star-rating-card");

      // Background color comes from the JSON — each record can have its own color
      card.style.backgroundColor = record.color;

      // ── Record text ─────────────────────────────────────────
      const text = document.createElement("span");
      text.innerText = record.text;
      text.classList.add("star-rating-card-text");
      card.appendChild(text);

      // ── Copy button (conditional) ────────────────────────────
      // Only renders if "copyEnabled": true in the record's JSON
      if (record.copyEnabled) {
        const copyBtn = document.createElement("button");
        copyBtn.innerText = "Copy";
        copyBtn.classList.add("star-rating-copy-btn");

        copyBtn.onclick = () => {
          // Clipboard API — copies the record text to the clipboard
          navigator.clipboard.writeText(record.text)
            .then(() => {
              // Visual success feedback — changes button text for 1.5s
              copyBtn.innerText = "Copied ✓";
              return setTimeout(() => { copyBtn.innerText = "Copy"; }, 1500);
            })
            .catch(() => {
              // Visual error feedback — e.g. browser blocked clipboard access
              copyBtn.innerText = "Error copying";
            });
        };

        card.appendChild(copyBtn);
      }

      recordsContainer.appendChild(card);
    });

    this._container.appendChild(recordsContainer);
  }
}
